version : "3"

services :
    nginx :
        container_name : nginx
        build : ./requirements/nginx
        volumes :
            - wp_vol:/var/www/html/wordpress
            - adminer_vol:/var/www/html/adminer
        networks :
            - my_net
        depends_on :
            - wordpress
            - ftp-srv
            - node_js
        ports : 
            - "443:443"

    wordpress:
        volumes :
            - wp_vol:/var/www/html/wordpress
        container_name: wordpress
        build : ./requirements/wordpress
        env_file:
            - .env
        depends_on:
            -   mariadb
            -   redis
        networks : 
            - my_net


    mariadb:
        volumes:
            - db_vol:/var/lib/mysql
        container_name: mariadb
        build : ./requirements/mariadb
        env_file:
            - .env
        networks:
            - my_net
    
    ftp-srv :
        container_name : ftp-srv
        build : ./requirements/bonus/ftp
        ports:
            - "20:20"
            - "21:21"
        volumes: 
            - wp_vol:/shared_fold
        networks:
            - my_net
    redis:
        container_name: redis
        build : ./requirements/bonus/redis
        networks:
            - my_net
    
    adminer :
        container_name: adminer
        build : ./requirements/bonus/adminer
        env_file:
            - .env
        networks:
            - my_net
        volumes:
            - adminer_vol:/var/www/html/adminer/
    node_js :
        container_name: node_js
        build : ./requirements/bonus/node_js
        networks:
            - my_net
        ports:
            - "3000:3000"
       
networks :
        - my_net

volumes :
    wp_vol:
        name : wp_vol   
        driver: local
        driver_opts :
            type: none
            o: bind
            device : /home/techies/volume/
    adminer_vol:
        name : adminer_vol  
        driver: local
        driver_opts :
            type: none
            o: bind
            device : /home/techies/adminer_vol/
    db_vol:
        name: db_vol
        driver: local
        driver_opts :
            type: none
            o: bind
            device : /home/techies/db_vol/

networks :
    my_net :
        driver : bridge
